server:
  port: 8081
  servlet:
    context-path: /v1.0/
spring:
  datasource:
    driver-Class-Name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/colegio
    username: root
    password: 
    hikari:
      max-lifetime: 300000        
      maximumPoolSize: 100
      connectionTimeout: 3600000
  profiles: develop
  application:
    name: app-cre-landing-formularios-api
    version: develop    
StoredProcedures:
  insertProfesor: CALL SP_COLEGIO_INSERT_PROFESOR(:p_nombres,:p_apellidos,:p_tipo_identificacion,:p_numero_identificacion,:p_correo,:p_celular,:p_materia,:p_edad)
  updateProfesor: CALL SP_COLEGIO_UPDATE_PROFESOR(:p_id_profesor,:p_nombres,:p_apellidos,:p_tipo_identificacion,:p_numero_identificacion,:p_correo,:p_celular,:p_materia,:p_edad)
  deleteProfesor: CALL SP_COLEGIO_DELETE_PROFESOR(:p_id_profesor)
  selectProfesor: CALL SP_COLEGIO_SELECT_PROFESOR()
  
  insertMateria: CALL SP_COLEGIO_INSERT_MATERIA(:p_nombres,:p_apellidos,:p_tipo_identificacion,:p_numero_identificacion,:p_correo,:p_celular,:p_materia,:p_edad)
  updateMateria: CALL SP_COLEGIO_UPDATE_MATERIA(:p_id_materia,:p_nombres,:p_apellidos,:p_tipo_identificacion,:p_numero_identificacion,:p_correo,:p_celular,:p_materia,:p_edad)
  deleteMateria: CALL SP_COLEGIO_DELETE_MATERIA(:p_id_materia)
  selectMateria: CALL SP_COLEGIO_SELECT_MATERIA()
  
  selectDocumentos: CALL SP_COLEGIO_SELECT_DOCS()
  
  insertEstudiante: CALL SP_COLEGIO_INSERT_ESTUDIANTE(:p_nombres,:p_apellidos,:p_tipo_identificacion,:p_numero_identificacion,:p_correo,:p_celular,:p_edad)
  updateEstudiante: CALL SP_COLEGIO_UPDATE_ESTUDIANTE(:p_id_estudiante,:p_nombres,:p_apellidos,:p_tipo_identificacion,:p_numero_identificacion,:p_correo,:p_celular,:p_edad)
  deleteEstudiante: CALL SP_COLEGIO_DELETE_ESTUDIANTE(:p_id_estudiante)
  selectEstudiante: CALL SP_COLEGIO_SELECT_ESTUDIANTE()